### ISSUE TITLE
openvpn-auth-ldap package is available in epel 6 repos

### ISSUE THREAD

**Issue by earsdown** [voxpupuli/puppet-openvpn#172]
Hey,
Doesn't affect me, but it looks like openvpn-auth-ldap is available in the EPEL 6 repos for redhat/centos 6.x machines.
Cheers

**Comment by luxflux** [comment]
Thanks for the heads up. I will leave this open, if anyone wants to implement this, I am open to PRs.

**Comment by luxflux** [comment]
Also see [this discussion](https://github.com/luxflux/puppet-openvpn/commit/bae0c0e193306c3f03b81d2ed61e710dee4d6a68#commitcomment-13612143).

**Comment by ciobancai** [comment]
The following package for "openvpn-auth-ldap" is not require to be installed on RHEL7. The plugin is already include with the latest openvpn package and can be found at this location: /usr/lib64/openvpn/plugins/openvpn-plugin-auth-pam.so

I'm using openvpn-2.3.10-1.el7.x86_64 and worked OK

**Comment by WetHippie** [comment]
I'm stuck with this as well (Centos 7 here).  Even manually installing the plugin off the command line does not allow the installation to proceed.

**Comment by WetHippie** [comment]
By using the PAM module, my openvpn will allow access directly without needing other modules. I already have a global PAM -> LDAP configuration running, so this just makes use of that.  On Centos7 the path and filename are different, so I've just pushed in conditional path selection based on version.

**Comment by ekohl** [comment]
Looks like the data is set for EL6
https://github.com/voxpupuli/puppet-openvpn/blob/258ac2b5834726cf2ca4df70caa3888403586a89/data/family/RedHat/6.yaml#L1-L2

Closing this. If a similar fix is needed for EL7 then please open a new issue.
