### ISSUE TITLE
Should be an option to install openvpn from http://swupdate.openvpn.net/ repo

### ISSUE THREAD

**Issue by law** [voxpupuli/puppet-openvpn#218]
Currently (at least on Xenial), the module installs the distro openvpn package.  It would be nice if there was a 'manage_repo' or similar option that would have the module install/manage the official http://swupdate.openvpn.net/ repo so the latest open-source openvpn packages can be installed, rather than wait on security backports to make their way downstream.

**Comment by Dan33l** [comment]
Since they does not propose Debian 9 or Ubuntu 18.04, it does not look updated so often.
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
Not updated since 14 month.

This is not a high priority change for us. A pull request would be considered.
