### ISSUE TITLE
OpenVPN is now generating blank/empty user certificates

### ISSUE THREAD

**Issue by law** [voxpupuli/puppet-openvpn#225]
I've been using OpenVPN 2.4.0-xenial0 from the  http://build.openvpn.net/debian/openvpn/stable repo, managed by version 4.0.1 of this module, on Puppet 4.8.x.  As of today, new client-certs generated with this module have a length of 0 bytes, although each of the puppet-commands appears to run without error.  /etc/openvpn/mycorp/easy-rsa/keys/serial.txt does not appear to be updating either.  My production hiera data looks like: 
```
openvpn::clients:
  'lots': {}
  'of': {}
  'users': {}
  'go': {}
  'here': {}

openvpn::servers:
  'mycorp':
    country: 'US'
    province: 'CA'
    city: 'Sonoma'
    organization: 'mycorp'
    email: 'devops@mycorp.com'
    server: '10.254.0.0 255.255.255.0'
    proto: 'udp'
    persist_key: true
    persist_tun: true
    push: ['dhcp-option DNS 172.33.0.2','route 172.33.0.0 255.255.0.0']
    dev: 'tun'
    ipp: true
    keepalive: "10 120"
    logfile: '/var/log/openvpn.log'
    topology: 'subnet'
    verb: '3'
    local: ''
    ssl_key_size: '4096'
```

this all seems to create an appropriate openvpn server config, etc.  I'm at a loss as to how to further troubleshoot, but am open to ideas.

**Comment by luxflux** [comment]
Hm, did you try to run puppet with debug on? It looks like running a script goes wrong...

**Comment by Dan33l** [comment]
Since acceptance tests setup a client /server config, we can probably close this issue. #310
