### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by luxflux** [voxpupuli/puppet-openvpn#228]
As the users of this module maybe already noticed, but the release cycles and feedback on PRs/Issues has increased. This is mostly related to the point that I'm not doing any puppet stuff anymore at work and I spend my free time more with my kids than with my computers...

For this reasons I'd like to involve more people and pass on ownership fully or partially to another person or a group of people.
Please reach out to me via mail (raffael@yux.ch) if you'd like to take over some work.

**Comment by elisiano** [comment]
@luxflux you may want to donate the module to Vox Pupuli (they adopt and maintain puppet modules whose maintainers cannot maintain anymore).

https://voxpupuli.org/
https://github.com/voxpupuli

**Comment by luxflux** [comment]
Thanks for the tip, @elisiano. I'll have a look there as well.

**Comment by WetHippie** [comment]
I'd be willing to help, but I'm far too new to puppet to be able to fully maintain. Lots of little things I can do, but full-blow module maintenance is beyond my knowledge currently. I've only been using puppet for 4 weeks!

**Comment by bastelfreak** [comment]
Hi,
I'm one of the Vox Pupuli members. We're happy to host your module. If you are interested in migrating it than let us know. The best way to discuss is probably in our IRC channel, #voxpupuli on freenode.

**Comment by galgalesh** [comment]
Hi @luxflux 

I'm the maintainer of the [OpenVPN Juju Charm](https://jujucharms.com/openvpn/) which uses this Puppet module to do the heavy lifting. Thanks for this module, it makes my life a lot easier!

I'd be happy to fix the bugs I'm running into, but I don't have the Puppet knowledge and the bandwidth to be a full maintainer.

I think migrating to Vox Pupuli is the best option.

**Comment by cjeanneret** [comment]
Hello @luxflux 
Any news regarding the possible hosting by Vox Pupuli?

Cheers,

C.

**Comment by luxflux** [comment]
Thanks for all the comments here. I will reach out to Vox Pupuli to see if they can take over this module.
