### ISSUE TITLE
error in File["${etc_directory}/openvpn/${name}"] dependencies

### ISSUE THREAD

**Issue by khaefeli** [voxpupuli/puppet-openvpn#232]
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Invalid relationship: Exec[copy easy-rsa to openvpn config folder zh] { require => File[/etc/openvpn/zh] }, because File[/etc/openvpn/zh] doesn't seem to be in the catalog
`
the require comes from ca.pp line 124:
`    #require => File["${etc_directory}/openvpn/${name}"],`

edit: looks like the `openvpn::params` aren't loaded inside of the `openvpn::server` with puppet 4.9x and e.g. the etc_directory variable is empty.

if I inherit the params with the openvpn class, everything works like expected

**Comment by Dan33l** [comment]
It should not be present with the current version of module.
You are welcome to reopen if the issue is yet present.
