### ISSUE TITLE
debian 7 support broken

### ISSUE THREAD

**Issue by Dan33l** [voxpupuli/puppet-openvpn#291]
## Affected Puppet, Ruby, OS and module versions/distributions

operating system debian 7

## How to reproduce (e.g Puppet code you use)

```
      openvpn::server { 'test_openvpn_server':
        country      => 'FR',
        province     => 'Occitanie',
        city         => 'France',
        organization => 'FOO',
        email        => 'bar@foo.org',
        server       => '10.0.0.0 255.255.255.0',
        local        => '',
      }
```

## What are you seeing

When this module is used on debian 7, the current settings about cipher with a so old operating system, does not work. The service `openvpn` does not start

## What behaviour did you expect instead

process `openvpn` started.

## Output log

The start of openvpn server log the following : 
`Problem with cipher list: TLS-DHE-RSA-WITH-AES-256-GCM-SHA384:TLS-DHE-RSA-WITH-AES-256-CBC-SHA256:TLS-DHE-RSA-WITH-AES-128-GCM-SHA256:TLS-DHE-RSA-WITH-AES-128-CBC-SHA256: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match`

If removing debian 7 support is considered as possible option,  i can provide a PR.

**Comment by Dan33l** [comment]
debian 7 is removed from `metadata.json`, but code is yet present in module.

**Comment by bastelfreak** [comment]
Hi @Dan33l. Debian 7 isn't supported anymore. Can you please provide a PR to remove the related code?

**Comment by Dan33l** [comment]
Yes. Before, i wanted to work about EasyRSA PR #292 .
