### ISSUE TITLE
Failures after upgrade

### ISSUE THREAD

**Issue by ju5t** [voxpupuli/puppet-openvpn#303]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: 1.8.7 (unfortunately this is the default in CentOS 6) (client), 2.0.0p648 (server)
- Distribution: CentOS 6 (client), CentOS 7 (server)
- Module version: 7.4.0

We've upgraded from version 4.0.1. I couldn't see anything related in the changelog but perhaps I've missed it?

## How to reproduce

I've left out the country, etc., they are all valid details. We're pushing a few routes but I don't think it's related.

```
  openvpn::server { 'vpn.domain':
    country      => '...',
    province     => '...',
    city         => '...',
    organization => '...',
    email        => '...',
    server       => 'internal subnet,
    server_ipv6  => '',
    topology     => 'subnet',
    proto        => 'tcp-server',
    duplicate_cn => true,
    push         => [
      ...
    ],
  }
```

## What are you seeing

```
Info: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/File[/etc/openvpn/vpn.domain/easy-rsa/vars]: Filebucketed /etc/openvpn/vpn.domain/easy-rsa/vars to puppet with sum 8589db4e716c1d7cabc4abe34394973a
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/File[/etc/openvpn/vpn.domain/easy-rsa/vars]/content: content changed '{md5}8589db4e716c1d7cabc4abe34394973a' to '{md5}32c06f70a162f6af40ab05dcf9372206'
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/File[/etc/openvpn/vpn.domain/easy-rsa/openssl.cnf]/target: target changed '/etc/openvpn/vpn.domain/easy-rsa/openssl-1.0.0.cnf' to '/etc/openvpn/vpn.domain/easy-rsa/openssl-1.0.cnf'
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns: NOTE: If you run ./clean-all, I will be doing a rm -rf on
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns:
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns: Note: using Easy-RSA configuration from: ./vars
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns:
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns: Easy-RSA error:
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns:
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns: Missing expected directory: private (perhaps you need to run init-pki?)
Notice: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns: Run easyrsa without commands for usage and command help.
Error: './easyrsa build-server-full server nopass' returned 1 instead of one of [0]
Error: /Stage[main]/Profiles::Openvpn/Openvpn::Server[vpn.domain]/Openvpn::Ca[vpn.domain]/Exec[generate server cert vpn.domain]/returns: change from notrun to 0 failed: './easyrsa build-server-full server nopass' returned 1 instead of one of [0]
```

## What behaviour did you expect instead

I expected it to run without errors.

What am I missing here?

**Comment by bastelfreak** [comment]
@Dan33l can you look into this?

**Comment by ju5t** [comment]
By default it's 3.0.3-1 on CentOS 6. This is coming from epel.

**Comment by Dan33l** [comment]
The module version `4.0.1` did not exist if a search on Puppet forge. Did you mean `4.1.0` ?

**Comment by Dan33l** [comment]
With last puppet4 and ruby 2.5.1 and last version of module code it works without error with the following puppet code :  
```
        openvpn::server { 'vpn.domain':
          country      => 'CO',
          province     => 'ST',
          city         => 'A city',
          organization => 'FOO',
          email        => 'bar@foo.org',
          server       => '10.0.0.0 255.255.255.0',
          server_ipv6  => '',
          topology     => 'subnet',
          proto        => 'tcp-server',
          duplicate_cn => true,
        }
```

**Comment by Dan33l** [comment]
@ju5t puppet module `luxflux-openvpn-4.0.1` works only with  `easyrsa2`.

The file `/etc/openvpn/vpn.domain/easy-rsa/keys/ca.key`, was it already existing on your `easyrsa2` setup ? How was you using `easyrsa3` with puppet module `luxflux-openvpn-4.0.1` ?

The [exec initca](https://github.com/voxpupuli/puppet-openvpn/blob/master/manifests/ca.pp#L230) creates this file and the directory `private`.

**Comment by Dan33l** [comment]
> We have always run OpenVPN with Puppet. We never made any changes to `easyrsa`, neither version 2 or 3. The `ca.key` file has been there since the beginning.

So, please confirm i well understood your path : 
 * puppet with module `luxflux-openvpn-4.0.1` installed `easyrsa2` and root certificat and clients certificats.
 * then `easyrsa3` was release and pushed into EPEL mirrors. With `easyrsa3` and `luxflux-openvpn-4.0.1`, it was yet possible to produce new clients certificates.
* then you jumped to `puppet-openvpn-7.4.1` and you encountered the issue you reported.

Am i correct ? 

> 
> I assume that if we remove `ca.key` our clients would get new VPN keys too and we need to look for a different solution here?

Yes. If the current root certificate is lost, all client will be unable to use the service. And you will need to renew all certificates.

My advice is to backup, if not already done, all the pki stuffs in `/etc/openvpn/vpn.domain/easy-rsa`.

**Comment by ju5t** [comment]
I can only assume that we were using easyrsa2 before. I don't know for sure. This server is a little older by now so there are no installation logs of it. We haven't added new clients for a while either.

So basically, you suggest to backup the `easy-rsa` folder, remove `ca.key` and regenerate everything and renew the certificates for the clients that are on this server?

I think we can get away with that.

**Comment by Dan33l** [comment]
The short fix should be to stop openvpn process and then to remove the directory `/etc/openvpn/vpn.domain/easy-rsa`.
During next run puppet will produce a new fresh directory `easyrsa` with new certificates for a new pki.
And so you will need to change all certificates for all clients.

A less short fix that should permit to avoids having to change certificates for all clients : 
 * the short fix.
 * stop openvpn service
 * use your backup to put your old stuffs from `easyrsa2` in the right place expected by `easyrsa3`

**Comment by Dan33l** [comment]
May i consider closing this issue ?

**Comment by ju5t** [comment]
@Dan33l We decided to throw everything away and reissue all certificates. Everything else took a lot of time and caused all sorts of issues. Not sure if this is an OpenVPN issue, an issue with this module, our system or a combination of all three.

I'll close this.
