### ISSUE TITLE
Do not fail fatal if OS is unsupported.

### ISSUE THREAD

**Issue by jkroepke** [voxpupuli/puppet-openvpn#304]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.0.2
- Ruby:
- Distribution: Ubuntu 18.04
- Module version: 7.3.0

## What are you seeing
> Evaluation Error: Error while evaluating a Function Call, unsupported OS Ubuntu 18.04
## What behaviour did you expect instead
>  Just working
## Any additional information you'd like to impart

The module works totally fine under Ubuntu 18.04. I had no issues but I also do not test some edge cases.

Anyway please do not fail if the version is unsupported. I can understand if you auto config may not work for unsupported version but let the user the chance to configure the module manually.

**Comment by bastelfreak** [comment]
hey Jan, can you provide a PR for this?
