### ISSUE TITLE
crl auto renewal broken with easyrsa 3.0

### ISSUE THREAD

**Issue by jameskirsop** [voxpupuli/puppet-openvpn#318]
If `EASY_REQ_CN` and `EASYRSA_REQ_OU` aren't passed in the `openvpn::server` definition, and are blank (which is the default for those params in the `ca.pp` class definition, the vars template doesn't allow for setting the related environment vars.

When `crl_auto_renew => true`, the missing environment vars causes the auto CRL renew process to fail (silently) and the CRL expires when it shouldn't be doing so.

If these two variables are indeed manually set to empty strings, the renewal process works without a hitch. The 3.0 template therefore shouldn't have the conditional clauses around these two params, and instead always write them to the `easy-rsa/vars` file regardless of their contents.

**Comment by Dan33l** [comment]
@jameskirsop thank you to report this bug.

With settings from the acceptance tests, if i run manually the renew like module do : 
```
[root@localhost /]# cd /etc/openvpn/test_openvpn_server/easy-rsa/
[root@localhost easy-rsa]# . ./vars && KEY_CN='' KEY_OU='' KEY_NAME='' KEY_ALTNAMES='' openssl ca -gencrl -out /etc/openvpn/test_openvpn_server/crl.pem -config /etc/openvpn/test_openvpn_server/easy-rsa/openssl.cnf
NOTE: If you run ./clean-all, I will be doing a rm -rf on
Using configuration from /etc/openvpn/test_openvpn_server/easy-rsa/openssl.cnf
error on line 71 of config file '/etc/openvpn/test_openvpn_server/easy-rsa/openssl.cnf'
140029667247944:error:0E065068:configuration file routines:STR_COPY:variable has no value:conf_def.c:618:line 71
```
And so it fail to renew.

I'll read your PR. But, currently the PR have some failing tests.

**Comment by Dan33l** [comment]
With EasyRsa version 3, it looks that in batch mode `--req-cn` is mandatory with CLI or variable `EASYRSA_REQ_CN`: 
https://github.com/OpenVPN/easy-rsa/commit/b0494ab24391d1e12ce376d461d2bb511fa3b035#diff-c42b27e9ddb5ec961577b91fd60d7301R106
