### ISSUE TITLE
Apparently openvpn 2.4 needs double quotes around client specific push options

### ISSUE THREAD

**Issue by qs5779** [voxpupuli/puppet-openvpn#329]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Ruby: 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
- Distribution: debian/stretch
- Module version: 8.1.0

## What are you seeing
In my logs I get this error when clients using redirect_gateway: true connect

<redacted>: <redacted> [<redacted>] Peer Connection Initiated with [AF_INET]<redacted>:18068
<redacted>: <redacted>:18068 Options error: Unrecognized option or missing or extra parameter(s) in /etc/openvpn/tejas/client-configs/<redacted>:2: push (2.4.0)

## What behaviour did you expect instead

No errors

## Output log
see above

## Any additional information you'd like to impart
found this report: https://forums.openvpn.net/viewtopic.php?t=23184https://forums.openvpn.net/viewtopic.php?t=23184

so i modified the template to put double quotes around all push options, now i have NO errors on connect and devices actually send traffic over the vpn, I would have submitted a PR, but I don't have an adequate test environment at the moment.

here is my fix diff

index e96edfc..750de0c 100644
--- a/templates/client_specific_config.erb
+++ b/templates/client_specific_config.erb
@@ -8,10 +8,10 @@ iroute-ipv6 <%= iroute_ipv6 %>
 ifconfig-push <%= ifconfig %>
 <% end -%>
 <% @dhcp_options.each do |option| -%>
-push dhcp-option <%= option %>
+push "dhcp-option <%= option %>"
 <% end -%>
 <% if @redirect_gateway -%>
-push redirect-gateway def1
+push "redirect-gateway def1"
 <% end -%>
 <% @route.each do |route| -%>
 push "route <%= route %>"

**Comment by bastelfreak** [comment]
hey @qs5779, thanks for reporting this. Are you able to provide a PR with the fix?

**Comment by qs5779** [comment]
Yes I can submit a PR but I can't provide any test from spec. I am struggling with gems on my laptop
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 2/23/19, 2:07 PM Tim Meusel <notifications@github.com> wrote:
hey @qs5779, thanks for reporting this. Are you able to provide a PR with the fix?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/voxpupuli/puppet-openvpn","title":"voxpupuli/puppet-openvpn","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/voxpupuli/puppet-openvpn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bastelfreak in #329: hey @qs5779, thanks for reporting this. Are you able to provide a PR with the fix?"}],"action":{"name":"View Issue","url":"https://github.com/voxpupuli/puppet-openvpn/issues/329#issuecomment-466680397"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/voxpupuli/puppet-openvpn/issues/329#issuecomment-466680397",
"url": "https://github.com/voxpupuli/puppet-openvpn/issues/329#issuecomment-466680397",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alexjfisher** [comment]
@qs5779 It's fine to let travis do all your testing if you can't set up an environment locally.  Just amend your commit with updates to tests and force push.  Travis will automatically run the tests again.
Looking at the travis [logs](https://travis-ci.org/voxpupuli/puppet-openvpn/jobs/497768209), probably just these two lines need updating. https://github.com/voxpupuli/puppet-openvpn/blob/ba394386b67703fd6742eddbf87838487bbf5f21/spec/defines/openvpn_client_specific_config_spec.rb#L54-L55

**Comment by Dan33l** [comment]
closed with #330
