### ISSUE TITLE
Revoke command missing on easy-rsa 3.0

### ISSUE THREAD

**Issue by jasonsattler** [voxpupuli/puppet-openvpn#331]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.10
- Ruby: ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
- Distribution: centos
- Module version: any
- easy-rsa version: 3.0.3-1.el7.noarch

## What are you seeing
easy-rsa change the way they revoke.  
They no longer have `./revoke-full`

It is now `./easyrsa revoke`
When I do it manually it will ask you to confirm that you want to delete by typing `yes`.

Then I had to create a new `/etc/openvpn/<server>/crl.pem` by running `./easyrsa gen-crl`
Then restart the openvpn server

**Comment by bastelfreak** [comment]
Hi @jasonsattler, thanks for reporting this. Are you able to provide a PR with a fix or an acceptance test for this?

**Comment by jasonsattler** [comment]
I will work on a fix

**Comment by Dan33l** [comment]
I reopen this issue because PR #338 is opened.
