### ISSUE TITLE
openvpn server was deployed on all puppet agents

### ISSUE THREAD

**Issue by wqbbs911** [voxpupuli/puppet-openvpn#351]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:5.5.1-1
- Ruby:
- Distribution:
- Module version: 8.2.0

## How to reproduce (e.g Puppet code you use)
only set below in manifests for vpn server cws122.pp :
openvpn::server { 'cws122':
    country      => 'XXX',
    province     => 'XXX',
    city         => 'XXX',
    organization => 'XXX',
    email        => 'test@123.org',
    server       => '10.200.200.0 255.255.255.0',
    local        => "$::ipaddress_enp4s0",
  }

   openvpn::client {
     'kong':
       server      => 'cws122',
       remote_host => '192.168.196.122',
    }

 openvpn::deploy::export { 'kong':
    server => 'cws122',
}
## What are you seeing
other all puppet agents will install openvpn server cws122 and configuration file as well

## What behaviour did you expect instead
only specify instance install openvpn server

**Comment by Dan33l** [comment]
The module deploy openvpn server where the owner of the puppet server define it have to be deployed. I don't understand why open an issue here.

**Comment by wqbbs911** [comment]
but openvpn server configuration were deployed on all puppet instances and service was started, any options i missed ?

**Comment by Dan33l** [comment]
You need to define  where a puppet code have to be applied (or not applied).
The standard way to define this is to use roles and profiles.
Some readings:
https://puppet.com/docs/pe/2017.2/r_n_p_full_example.html
https://rnelson0.com/2017/03/08/what-goes-in-a-puppet-role-or-profile/

**Comment by wqbbs911** [comment]
it works now, tnx
