### ISSUE TITLE
Client configurations with the new Deferred function aren't working

### ISSUE THREAD

**Issue by erik-frontify** [voxpupuli/puppet-openvpn#421]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.13
- Puppetserver: 7.5
- Ruby: 2.7.4
- Distribution: RHEL
- Module version: master

## How to reproduce (e.g Puppet code you use)
export client vpn configuration on the vpn server
```puppet
ensure_resources('openvpn::deploy::export', {myuser => {server => myserver}})
include client vpn configuration on the client
openvpn::deploy::client { myuser:
  server => myserver,
  manage_etc => false,
}  
```
## What are you seeing
The client configuration file contains:
```
Deferred({'name' => 'openvpn::file_content', 'arguments' => ['/etc/openvpn/myserver/download-configs/myuser/myuser.conf']})
```
## What behaviour did you expect instead
A valid client configuration as it was with the export using facts instead of deferred.

**Comment by jameskirsop** [comment]
I'm also seeing this behaviour on a Puppet 6 deployment with a RHEL 8 server as the OpenVPN server with Ubuntu clients.

**Comment by jkroepke** [comment]
Did you test it without using ensure_resources?

**Comment by jameskirsop** [comment]
@jkroepke, unlike @erik-frontify, I'm not using `ensure_resources` anywhere in my manifests.

I created a custom definition so I could keep things DRY:
```
define openvpn_client (
  String $host = $title,
  String $ifconfig_address,
  String $server = "nms",
  String $ensure = 'present',
  ) {
	openvpn::client { $name:
 		server => $server,
 		proto => 'udp',
	} ->
	openvpn::client_specific_config { $name:
 		server => $server,
 		ifconfig => $ifconfig_address,
		ensure => $ensure,
	}
	openvpn::deploy::export { $name:
		server => $server,
	}
}
```

and the following in my client manifest:
```
openvpn::deploy::client { $fqdn:
	server => 'rhel8',
}
```

**Comment by jkroepke** [comment]
I reproduce your config and I agree. It would not work. By reading the documentation how exported resources work, it could never work.

I'm will create a PR as proposal to remove the the deploy functionality from the module.
